"""added current_price fetched from alpha vantage api

Revision ID: 4312b01a127d
Revises: 4f494d6d1000
Create Date: 2022-02-13 13:44:47.357488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4312b01a127d'
down_revision = '4f494d6d1000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('current_price', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('current_price_date', sa.DateTime(), nullable=True))
    op.add_column('stocks', sa.Column('position_value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'position_value')
    op.drop_column('stocks', 'current_price_date')
    op.drop_column('stocks', 'current_price')
    # ### end Alembic commands ###
