"""added purchase_date to the Stock model

Revision ID: 4f494d6d1000
Revises: df472f9e977f
Create Date: 2022-02-13 06:35:05.343296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f494d6d1000'
down_revision = 'df472f9e977f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('purchase_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'purchase_date')
    # ### end Alembic commands ###
