"""established one-to-manyrelationship between stocks and users tables

Revision ID: df472f9e977f
Revises: e1bfd0665aa7
Create Date: 2022-02-13 06:21:09.061930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df472f9e977f'
down_revision = 'e1bfd0665aa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'stocks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stocks', type_='foreignkey')
    op.drop_column('stocks', 'user_id')
    # ### end Alembic commands ###
